/*
 * Copyright 2026 The Apache Software Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
  id 'java-library'
}

repositories {
  mavenCentral()
}

configurations {
  standalone
  workerA
  workerB
}

dependencies {
  standalone 'org.apache.commons:commons-lang3:3.18.0'
  workerA 'com.google.guava:guava:33.4.8-jre'
  workerB 'commons-io:commons-io:2.18.0'
}

def registerResolver = { taskName, configurationName ->
  tasks.register(taskName) {
    doLast {
      configurations.named(configurationName).get().files.each { file ->
        println("resolved ${configurationName}: ${file.name}")
      }
    }
  }
}

registerResolver('resolveStandalone', 'standalone')
registerResolver('resolveWorkerA', 'workerA')
registerResolver('resolveWorkerB', 'workerB')